version: '3'
services:
  osrmcpy-jupyter:
    build: .
    volumes:
      - ./:/usr/local/app
    ports:
      - '8888:8888'
    command: jupyter lab --NotebookApp.token= --ip=0.0.0.0 --no-browser --allow-root
